[package]
distribution = "2201.13.4"
org = "ballerinax"
name = "huggingface.tgi"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [
    "AI/Chat",
    "AI/Text Generation",
    "HuggingFace",
    "TGI",
    "LLM",
    "OpenAI Compatible",
    "Streaming",
    "Inference",
    "Llama",
    "Mistral",
    "Vendor/HuggingFace",
    "Cost/Free"
]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-huggingface.tgi"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
