// Generated by Ballerina OpenAPI tool and manually sanitized.
// See docs/spec/sanitations.md for changes made post-generation.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

public type GrammarTypeGrammarTypeGrammarTypeOneOf123 record {
    "json_schema" 'type;
    JsonSchemaConfig value;
};

public type MessageContent MessageContentOneOf1|MessageContentMessageContentOneOf12;

public type ToolCall record {
    FunctionDefinition 'function;
    string id;
    string 'type;
};

public type StreamOptions record {
    # If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value
    @jsondata:Name {value: "include_usage"}
    boolean includeUsage?;
};

public type CompletionComplete record {
    @jsondata:Name {value: "finish_reason"}
    string finishReason;
    @constraint:Int {minValue: 0}
    int:Signed32 index;
    string text;
    float[]? logprobs?;
};

public type MessageChunkOneOf1 record {
    string text;
    "text" 'type;
};

public type GrammarType GrammarTypeOneOf1|GrammarTypeGrammarTypeOneOf12|GrammarTypeGrammarTypeGrammarTypeOneOf123;

public type CompatGenerateRequest record {
    boolean 'stream = false;
    string inputs;
    GenerateParameters parameters?;
};

public type Token record {
    boolean special;
    float? logprob;
    @constraint:Int {minValue: 0}
    int:Signed32 id;
    string text;
};

public type SagemakerResponse GenerateResponse|ChatCompletion|CompletionFinal;

public type FinishReason "length"|"eos_token"|"stop_sequence";

public type FunctionName record {
    string name;
};

public type FunctionDefinition record {
    string name;
    string? description?;
    anydata arguments;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Bearer token configuration for Hugging Face authentication.
    # Required for gated models (e.g., Llama) and private/dedicated TGI endpoints.
    # Example: { token: "hf_xxxx" }. Obtain your token at https://huggingface.co/settings/tokens
    @display {label: "HF Auth Config"}
    http:BearerTokenConfig auth?;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type Tool record {
    FunctionDefinition 'function;
    string 'type;
};

public type MessageContentMessageContentOneOf12 MessageChunk[];

public type TokenizeResponse SimpleToken[];

public type PrefillToken record {
    float? logprob;
    @constraint:Int {minValue: 0}
    int:Signed32 id;
    string text;
};

public type ChatCompletion record {
    @constraint:Int {minValue: 0}
    int created;
    Usage usage;
    string model;
    string id;
    ChatCompletionComplete[] choices;
    @jsondata:Name {value: "system_fingerprint"}
    string systemFingerprint;
};

public type Details record {
    @jsondata:Name {value: "finish_reason"}
    FinishReason finishReason;
    @jsondata:Name {value: "top_tokens"}
    Token[][] topTokens?;
    int? seed?;
    @jsondata:Name {value: "generated_tokens"}
    int:Signed32 generatedTokens;
    PrefillToken[] prefill;
    Token[] tokens;
    @jsondata:Name {value: "best_of_sequences"}
    BestOfSequence[]? bestOfSequences?;
};

# <https://platform.openai.com/docs/guides/function-calling/configuring-function-calling-behavior-using-the-tool_choice-parameter>
public type ToolChoice ToolChoiceOneOf1|ToolChoiceToolChoiceOneOf12|ToolChoiceToolChoiceToolChoiceOneOf123|ToolChoiceToolChoiceToolChoiceToolChoiceOneOf1234;

public type ChatCompletionLogprobs record {
    ChatCompletionLogprob[] content;
};

public type JsonSchemaConfig record {
    # The actual JSON schema definition
    anydata schema;
    # Optional name identifier for the schema
    string? name?;
};

# Means the model will not call any tool and instead generates a message
public type ToolChoiceToolChoiceOneOf12 "none";

public type TextMessage record {
    string role;
    @jsondata:Name {value: "tool_call_id"}
    string? toolCallId?;
    string content;
};

public type ModelInfo record {
    @constraint:Int {minValue: 0}
    int created;
    @jsondata:Name {value: "owned_by"}
    string ownedBy;
    string id;
    string 'object;
};

public type ToolChoiceToolChoiceToolChoiceToolChoiceOneOf1234 record {
    FunctionName 'function;
};

public type MessageChunkMessageChunkOneOf12 record {
    @jsondata:Name {value: "image_url"}
    Url imageUrl;
    "image_url" 'type;
};

// Sanitization note: `*MessageBody` (record inclusion) was removed because `MessageBody` is a
// union type (not a record), which is illegal for record inclusion in Ballerina.
// The two body variants' fields are inlined here as optional fields instead.
public type Message record {
    # Message content (text string or array of content chunks)
    MessageContent? content?;
    # Tool calls made by the assistant (mutually exclusive with content)
    @jsondata:Name {value: "tool_calls"}
    ToolCall[]? toolCalls?;
    string role;
    string? name?;
};

public type CompletionRequest record {
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the
    # tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered
    @jsondata:Name {value: "top_p"}
    float? topP?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far,
    # decreasing the model's likelihood to repeat the same line verbatim
    @jsondata:Name {value: "frequency_penalty"}
    float? frequencyPenalty?;
    int? seed?;
    # Up to 4 sequences where the API will stop generating further tokens
    string[]? stop?;
    # The maximum number of tokens that can be generated in the chat completion
    @jsondata:Name {value: "max_tokens"}
    int:Signed32? maxTokens?;
    boolean 'stream?;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while
    # lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both
    float? temperature?;
    # UNUSED
    # ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API
    string? model?;
    # The text to append to the prompt. This is useful for completing sentences or generating a paragraph of text.
    # please see the completion_template field in the model's tokenizer_config.json file for completion template
    string? suffix?;
    Prompt prompt;
    @jsondata:Name {value: "repetition_penalty"}
    float? repetitionPenalty?;
};

public type ChatCompletionComplete record {
    @jsondata:Name {value: "finish_reason"}
    string finishReason;
    @constraint:Int {minValue: 0}
    int:Signed32 index;
    OutputMessage message;
    ChatCompletionLogprobs? logprobs?;
};

public type ChatCompletionLogprob record {
    @jsondata:Name {value: "top_logprobs"}
    ChatCompletionTopLogprob[] topLogprobs;
    float logprob;
    string token;
};

public type Url record {
    string url;
};

public type SagemakerRequest CompatGenerateRequest|ChatRequest|CompletionRequest;

public type MessageChunk MessageChunkOneOf1|MessageChunkMessageChunkOneOf12;

public type GrammarTypeGrammarTypeOneOf12 record {
    "regex" 'type;
    string value;
};

public type ChatRequest record {
    # An integer between 0 and 5 specifying the number of most likely tokens to return at each token position, each with
    # an associated log probability. logprobs must be set to true if this parameter is used
    @jsondata:Name {value: "top_logprobs"}
    int:Signed32? topLogprobs?;
    # UNUSED
    # Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens
    # (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically,
    # the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model,
    # but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should
    # result in a ban or exclusive selection of the relevant token
    @jsondata:Name {value: "logit_bias"}
    float[]? logitBias?;
    int? seed?;
    # The maximum number of tokens that can be generated in the chat completion
    @jsondata:Name {value: "max_tokens"}
    int:Signed32? maxTokens?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far,
    # increasing the model's likelihood to talk about new topics
    @jsondata:Name {value: "presence_penalty"}
    float? presencePenalty?;
    # A prompt to be appended before the tools
    @jsondata:Name {value: "tool_prompt"}
    string? toolPrompt?;
    # A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of
    # functions the model may generate JSON inputs for
    Tool[]? tools?;
    # UNUSED
    # How many chat completion choices to generate for each input message. Note that you will be charged based on the
    # number of generated tokens across all of the choices. Keep n as 1 to minimize costs
    int:Signed32? n?;
    # Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each
    # output token returned in the content of message
    boolean? logprobs?;
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the
    # tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered
    @jsondata:Name {value: "top_p"}
    float? topP?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far,
    # decreasing the model's likelihood to repeat the same line verbatim
    @jsondata:Name {value: "frequency_penalty"}
    float? frequencyPenalty?;
    @jsondata:Name {value: "response_format"}
    GrammarType? responseFormat = ();
    # Up to 4 sequences where the API will stop generating further tokens
    string[]? stop?;
    boolean 'stream?;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while
    # lower values like 0.2 will make it more focused and deterministic.
    # 
    # We generally recommend altering this or `top_p` but not both
    float? temperature?;
    # A list of messages comprising the conversation so far
    Message[] messages;
    @jsondata:Name {value: "tool_choice"}
    ToolChoice? toolChoice = "auto";
    # [UNUSED] ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API
    string? model?;
    @jsondata:Name {value: "stream_options"}
    StreamOptions? streamOptions?;
};

public type BestOfSequence record {
    @jsondata:Name {value: "finish_reason"}
    FinishReason finishReason;
    @jsondata:Name {value: "top_tokens"}
    Token[][] topTokens?;
    int? seed?;
    @jsondata:Name {value: "generated_tokens"}
    int:Signed32 generatedTokens;
    PrefillToken[] prefill;
    Token[] tokens;
    @jsondata:Name {value: "generated_text"}
    string generatedText;
};

public type CompletionFinal record {
    @constraint:Int {minValue: 0}
    int created;
    Usage usage;
    string model;
    string id;
    CompletionComplete[] choices;
    @jsondata:Name {value: "system_fingerprint"}
    string systemFingerprint;
};

public type GenerateParameters record {
    # Watermarking with [A Watermark for Large Language Models](https://arxiv.org/abs/2301.10226)
    boolean watermark = false;
    # Random sampling seed
    int? seed?;
    # Activate logits sampling
    @jsondata:Name {value: "do_sample"}
    boolean doSample = false;
    # Top-p value for nucleus sampling
    @jsondata:Name {value: "top_p"}
    float? topP?;
    # The parameter for frequency penalty. 1.0 means no penalty
    # Penalize new tokens based on their existing frequency in the text so far,
    # decreasing the model's likelihood to repeat the same line verbatim
    @jsondata:Name {value: "frequency_penalty"}
    float? frequencyPenalty?;
    GrammarType? grammar = ();
    # Generate best_of sequences and return the one if the highest token logprobs
    @jsondata:Name {value: "best_of"}
    int? bestOf?;
    # Stop generating tokens if a member of `stop` is generated
    @constraint:Array {maxLength: 4}
    string[] stop?;
    # Truncate inputs tokens to the given size
    int? truncate?;
    # The number of highest probability vocabulary tokens to keep for top-n-filtering
    @jsondata:Name {value: "top_n_tokens"}
    int:Signed32? topNTokens?;
    # Maximum number of tokens to generate
    @jsondata:Name {value: "max_new_tokens"}
    int:Signed32? maxNewTokens?;
    # Whether to return decoder input token logprobs and ids
    @jsondata:Name {value: "decoder_input_details"}
    boolean decoderInputDetails = false;
    # The number of highest probability vocabulary tokens to keep for top-k-filtering
    @jsondata:Name {value: "top_k"}
    int:Signed32? topK?;
    # The value used to module the logits distribution
    float? temperature?;
    # Typical Decoding mass
    # See [Typical Decoding for Natural Language Generation](https://arxiv.org/abs/2202.00666) for more information
    @jsondata:Name {value: "typical_p"}
    float? typicalP?;
    # Lora adapter id
    @jsondata:Name {value: "adapter_id"}
    string? adapterId = ();
    # Whether to return generation details
    boolean details = true;
    # Whether to prepend the prompt to the generated text
    @jsondata:Name {value: "return_full_text"}
    boolean? returnFullText = false;
    # The parameter for repetition penalty. 1.0 means no penalty.
    # See [this paper](https://arxiv.org/pdf/1909.05858.pdf) for more details
    @jsondata:Name {value: "repetition_penalty"}
    float? repetitionPenalty?;
};

public type ChatCompletionTopLogprob record {
    float logprob;
    string token;
};

public type GrammarTypeOneOf1 record {
    "json" 'type;
    # A string that represents a [JSON Schema](https://json-schema.org/).
    # 
    # JSON Schema is a declarative language that allows to annotate JSON documents
    # with types and descriptions
    anydata value;
};

public type ChatTokenizeResponse record {
    @jsondata:Name {value: "templated_text"}
    string templatedText;
    @jsondata:Name {value: "tokenize_response"}
    TokenizeResponse tokenizeResponse;
};

public type MessageBodyOneOf1 record {
    MessageContent content;
};

public type Usage record {
    @jsondata:Name {value: "completion_tokens"}
    int:Signed32 completionTokens;
    @jsondata:Name {value: "prompt_tokens"}
    int:Signed32 promptTokens;
    @jsondata:Name {value: "total_tokens"}
    int:Signed32 totalTokens;
};

public type MessageBodyMessageBodyOneOf12 record {
    @jsondata:Name {value: "tool_calls"}
    ToolCall[] toolCalls;
};

public type GenerateResponse record {
    Details? details?;
    @jsondata:Name {value: "generated_text"}
    string generatedText;
};

public type ToolCallMessage record {
    string role;
    @jsondata:Name {value: "tool_calls"}
    ToolCall[] toolCalls;
};

public type Info record {
    # Router Parameters
    @jsondata:Name {value: "max_concurrent_requests"}
    int maxConcurrentRequests;
    @jsondata:Name {value: "validation_workers"}
    int validationWorkers;
    @jsondata:Name {value: "max_client_batch_size"}
    int maxClientBatchSize;
    @jsondata:Name {value: "max_best_of"}
    int maxBestOf;
    @jsondata:Name {value: "max_stop_sequences"}
    int maxStopSequences;
    # Model info
    @jsondata:Name {value: "model_id"}
    string modelId;
    string? sha?;
    string version;
    @jsondata:Name {value: "max_total_tokens"}
    int maxTotalTokens;
    # Router Info
    string router;
    @jsondata:Name {value: "model_pipeline_tag"}
    string? modelPipelineTag?;
    @jsondata:Name {value: "model_sha"}
    string? modelSha?;
    @jsondata:Name {value: "docker_label"}
    string? dockerLabel?;
    @jsondata:Name {value: "max_input_tokens"}
    int maxInputTokens;
};

public type MessageContentOneOf1 string;

public type GenerateRequest record {
    string inputs;
    GenerateParameters parameters?;
};

# Means the model must call one or more tools
public type ToolChoiceToolChoiceToolChoiceOneOf123 "required";

public type OutputMessage TextMessage|ToolCallMessage;

# Means the model can pick between generating a message or calling one or more tools
public type ToolChoiceOneOf1 "auto";

public type Prompt string[];

public type SimpleToken record {
    @constraint:Int {minValue: 0}
    int stop;
    @constraint:Int {minValue: 0}
    int 'start;
    @constraint:Int {minValue: 0}
    int:Signed32 id;
    string text;
};

public type MessageBody MessageBodyOneOf1|MessageBodyMessageBodyOneOf12;
